#!/usr/bin/env python3
# Copyright (c) 2021 The Toltec Contributors
# SPDX-License-Identifier: MIT

from toltec.repo import Repo

# Script parameters
recipes_dir = 'package'
work_dir = 'build/package'
repo_dir = 'build/repo'
remote = 'https://toltec-dev.org/testing'
fetch_missing = True

# Run build
repo = Repo(recipes_dir=recipes_dir, work_dir=work_dir, repo_dir=repo_dir)
repo.make_packages(remote=remote, fetch_missing=fetch_missing)
repo.make_index()
